# Generated by Django 3.2 on 2022-04-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafromcontactform',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='datafromcontactform',
            name='surname',
        ),
    ]
