# Generated by Django 3.2 on 2022-04-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20220407_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafromcontactform',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
