# Generated by Django 3.2 on 2022-04-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_resolution',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
