# Generated by Django 3.2 on 2022-04-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product_resolution',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
